/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import clases.Conexion;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfredo
 */
public class EditarProducto extends javax.swing.JFrame {

    private String producto = GestionarInventario.productoSelecionadoActual;

    /**
     * Creates new form GUI_EditarAlumno
     */
    public EditarProducto() {
        initComponents();
        this.setLocationRelativeTo(null);

        try {
            Connection cn = Conexion.conetar();
            PreparedStatement pst = cn.prepareStatement(
                    "select * from inventario where nombre = '" + producto + "'");

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                TEXTO_NOMBRE.setText(producto);
                TEXTO_CANTIDAD.setText(rs.getString("cantidad"));
                TEXTO_PRECIO.setText(rs.getString("precio_usd"));

            }

            cn.close();

        } catch (SQLException e) {
            System.err.println("ERROR al llamar al alumno:\n" + e);

            JOptionPane.showMessageDialog(null, "Error, contacte con el desarrollador del software");
        }

    }

    @Override
    public Image getIconImage() {
        Image setValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Protologo_3_192x192.png"));
        return setValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ELIMINAR = new javax.swing.JButton();
        TEXTO_NOMBRE = new javax.swing.JTextField();
        TEXTO_CANTIDAD = new javax.swing.JTextField();
        TEXTO_PRECIO = new javax.swing.JTextField();
        ACTUALIZAR = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar producto");
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Cantidad:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 60, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Precio:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 64, 40, 20));

        ELIMINAR.setBackground(new java.awt.Color(0, 0, 0));
        ELIMINAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ELIMINAR.setForeground(new java.awt.Color(255, 51, 51));
        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.setBorder(null);
        ELIMINAR.setFocusable(false);
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });
        getContentPane().add(ELIMINAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 89, 90, 20));

        TEXTO_NOMBRE.setBorder(null);
        getContentPane().add(TEXTO_NOMBRE, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 11, 318, 20));

        TEXTO_CANTIDAD.setBorder(null);
        getContentPane().add(TEXTO_CANTIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 37, 318, 20));

        TEXTO_PRECIO.setBorder(null);
        getContentPane().add(TEXTO_PRECIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 63, 318, 20));

        ACTUALIZAR.setBackground(new java.awt.Color(0, 0, 0));
        ACTUALIZAR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ACTUALIZAR.setForeground(new java.awt.Color(255, 255, 255));
        ACTUALIZAR.setText("ACTUALIZAR");
        ACTUALIZAR.setBorder(null);
        ACTUALIZAR.setFocusable(false);
        ACTUALIZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTUALIZARActionPerformed(evt);
            }
        });
        getContentPane().add(ACTUALIZAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_1000x1000.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ACTUALIZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTUALIZARActionPerformed

        int validacion = 0;

        String nombre, cantidad, precio;

        nombre = TEXTO_NOMBRE.getText().trim().toUpperCase();
        cantidad = TEXTO_CANTIDAD.getText().trim().toUpperCase();
        precio = TEXTO_PRECIO.getText().trim().toUpperCase();

        if (nombre.equals("")) {
            JOptionPane.showMessageDialog(null, "Nombre no puede estar vacio");
            validacion++;
        } else {
            validacion = 0;
        }
        if (cantidad.equals("")) {
            JOptionPane.showMessageDialog(null, "Cantidad no puede estar vacio");
            validacion++;
        } else {
            validacion = 0;
        }
        if (precio.equals("")) {
            JOptionPane.showMessageDialog(null, "Necesario el Precio");
            validacion++;
        } else {
            validacion = 0;
        }

        if (validacion == 0) {
            try {
                Connection cn = Conexion.conetar();
                PreparedStatement pst = cn.prepareStatement(
                        "update inventario set cantidad =?, precio_usd =?, nombre=? where nombre = '" + producto + "'");

                pst.setString(1, cantidad);
                pst.setString(2, precio);
                pst.setString(3, nombre);

                pst.executeUpdate();
                cn.close();

                JOptionPane.showMessageDialog(null, "Actualizacion exitosa");

                TEXTO_PRECIO.setText("");
                TEXTO_PRECIO.setText("");
                TEXTO_CANTIDAD.setText("");

                this.dispose();

            } catch (SQLException e) {
                System.err.println("ERROR al actualizar al especialista:\n" + e);

                JOptionPane.showMessageDialog(null, "Error, contacte con el desarrollador del software");
            }
        }

    }//GEN-LAST:event_ACTUALIZARActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        int estarSeguro = JOptionPane.showConfirmDialog(null, "¿Estás seguro de querer eliminar '" + producto + "'?");
        try {
            if (estarSeguro == 0) {
                Connection cn = Conexion.conetar();
                PreparedStatement pst = cn.prepareStatement(
                        "delete from inventario where nombre = '" + producto + "'");
                pst.executeUpdate();
                cn.close();
                JOptionPane.showMessageDialog(null, "Eliminado");
                this.dispose();
            }
        } catch (Exception e) {
            System.err.println("ERROR al eliminar al especialista:\n" + e);

            JOptionPane.showMessageDialog(null, "Error, contacte con el desarrollador del software");
        }
    }//GEN-LAST:event_ELIMINARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUALIZAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JTextField TEXTO_CANTIDAD;
    private javax.swing.JTextField TEXTO_NOMBRE;
    private javax.swing.JTextField TEXTO_PRECIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
