/*
 * 
 */
package gui;

import clases.Conexion;
import clases.PdfMaker;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Moises
 */
public class GestionarInventario extends javax.swing.JFrame {

    PdfMaker pdf = new PdfMaker();
    DefaultTableModel modelo = new DefaultTableModel();

    public static String productoSelecionadoActual = "";

    /**
     * Creates new form GUI_Primaria
     */
    public void CrearTabla() {
        TABLA_INVENTARIO = new JTable(modelo);
        SCROLL_DE_TABLA.setViewportView(TABLA_INVENTARIO);

        modelo.addColumn("Producto");
        modelo.addColumn("Cantidad");
    }

    public void ActualizarTabla() {
        try {
            Connection cn = Conexion.conetar();
            PreparedStatement pst = cn.prepareStatement(
                    "select nombre, cantidad from inventario order by nombre");

            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                Object[] fila = new Object[2];

                for (int i = 0; i < 2; i++) {
                    fila[i] = rs.getObject(i + 1);
                }
                modelo.addRow(fila);
            }

            cn.close();

        } catch (SQLException e) {
            System.err.println("ERROR AL LLENAR LA TABLA:\n" + e);
            JOptionPane.showMessageDialog(null, "Error, contacte con el desarrollador del software");
        }
    }

    private RegistrarProducto Aggp;

    public RegistrarProducto getRegistrarProducto() {
        if (Aggp == null) {
            return Aggp = new RegistrarProducto();
        } else {
            return Aggp;
        }

    }
    private Opciones instancia;

    public Opciones getOpciones() {
        if (instancia == null) {
            return instancia = new Opciones();
        } else {
            return instancia;
        }
    }

    public GestionarInventario() {
        initComponents();
        this.setLocationRelativeTo(null);

        /*Metodos para crear y llenar tabla*/
        CrearTabla();
        modelo.setRowCount(0);
        ActualizarTabla();

        /*Controlar los clicks con el mouse en la tabla*/
        TABLA_INVENTARIO.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int fila_poin = TABLA_INVENTARIO.rowAtPoint(e.getPoint());

                if (fila_poin > -1) {

                    productoSelecionadoActual = (String) modelo.getValueAt(fila_poin, 0);
                    EditarProducto getEditarProducto = new EditarProducto();
                    getEditarProducto.setVisible(true);

                }
                modelo.setRowCount(0);
                ActualizarTabla();
            }
        });

    }

    @Override
    public Image getIconImage() {
        Image setValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/Protologo_3_192x192.png"));
        return setValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SCROLL_DE_TABLA = new javax.swing.JScrollPane();
        TABLA_INVENTARIO = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MENU_REFRESCO = new javax.swing.JMenuItem();
        MUENU_AGREGAR_PRODUCTO = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestionar inventario");
        setIconImage(getIconImage());
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TABLA_INVENTARIO.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        SCROLL_DE_TABLA.setViewportView(TABLA_INVENTARIO);

        getContentPane().add(SCROLL_DE_TABLA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 480, 457));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo_1000x1000.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 480));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));
        jMenuBar1.setBorderPainted(false);

        jMenu1.setBackground(new java.awt.Color(0, 0, 0));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Opciones");

        MENU_REFRESCO.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK));
        MENU_REFRESCO.setText("Actualizar datos");
        MENU_REFRESCO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MENU_REFRESCOActionPerformed(evt);
            }
        });
        jMenu1.add(MENU_REFRESCO);

        MUENU_AGREGAR_PRODUCTO.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.ALT_MASK));
        MUENU_AGREGAR_PRODUCTO.setText("Agregar producto");
        MUENU_AGREGAR_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUENU_AGREGAR_PRODUCTOActionPerformed(evt);
            }
        });
        jMenu1.add(MUENU_AGREGAR_PRODUCTO);
        jMenu1.add(jSeparator2);

        jMenuItem2.setText("Obtener pdf inventario actual");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Volver a la ventana anterior");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MENU_REFRESCOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MENU_REFRESCOActionPerformed
        modelo.setRowCount(0);
        ActualizarTabla();
    }//GEN-LAST:event_MENU_REFRESCOActionPerformed

    private void MUENU_AGREGAR_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUENU_AGREGAR_PRODUCTOActionPerformed
        getRegistrarProducto().setVisible(true);
    }//GEN-LAST:event_MUENU_AGREGAR_PRODUCTOActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
        getOpciones().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        pdf.inventarioActual();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MENU_REFRESCO;
    private javax.swing.JMenuItem MUENU_AGREGAR_PRODUCTO;
    private javax.swing.JScrollPane SCROLL_DE_TABLA;
    private javax.swing.JTable TABLA_INVENTARIO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
